=== brandonyee333/test/definitions/liferay-resource-action-mapping_7_0_0.dtd
<!--
<!DOCTYPE resource-action-mapping PUBLIC
	"-//Liferay//DTD Resource Action Mapping 7.0.0//EN"
	"http://www.liferay.com/dtd/liferay-resource-action-mapping_7_0_0.dtd">
-->

<!--
The resource-action-mapping is the root of the deployment descriptor for a
resource action descriptor that is used to define actions that are supported
on portal resources such as portlets and models.
-->
<!ELEMENT resource-action-mapping (portlet-resource*, model-resource*,
resource*) >

<!--
The portlet-resource element defines the permissions of the portlet.
-->
<!ELEMENT portlet-resource (portlet-name, permissions?) >

<!--
The portlet-name element is the name of the portlet.
-->
<!ELEMENT portlet-name (#PCDATA) >

<!--
The permissions element defines the default permissions granted and unsupported
to community members, guests users, and layout managers.
-->
<!ELEMENT permissions (supports, (community-defaults | site-member-defaults)?,
guest-defaults?, guest-unsupported?, layout-manager?, owner-defaults?,
deprecated?) >

<!--
The supports element defines the actions supported by this resource.
-->
<!ELEMENT supports (action-key*) >

<!--
The action-key element defines the name of the action. The name will be
translated as specified in Language.properties. For example, if the action key
is "VIEW", then the key in Language.properties will be "action.VIEW".
-->

<!ELEMENT action-key (#PCDATA) >

<!--
The community-defaults element specifies the actions that community members are
permitted to perform by default. This element is deprecated and will be deleted
in future versions. Use the site-member-defaults element instead.
-->

<!ELEMENT community-defaults (action-key*) >

<!--
The site-defaults element specifies the actions that site members are
permitted to perform by default.
-->
<!ELEMENT site-member-defaults (action-key*) >

<!--
The guest-defaults element specifies the actions that guest users are permitted
to perform by default.
-->
<!ELEMENT guest-defaults (action-key*) >

<!--
The guest-unsupported element specifies the actions that guests are never
permitted to perform. This disables the ability to assign permissions for these
actions. Only define actions here if you wish to prevent anyone from granting
permissions to perform these actions.
-->
<!ELEMENT guest-unsupported (action-key*) >

<!--
The layout-manager element specifies the actions that layout managers are
permitted to perform. If omitted, then layout-managers are granted permissions
on all supported actions. If included, then layout managers can only perform
actions specified in this element.
-->
<!ELEMENT layout-manager (action-key*) >

<!--
The owner-defaults element specifies the actions that the creator of the
resource is permitted to perform. If omitted, then owners are granted
permissions on all supported actions.
-->
<!ELEMENT owner-defaults (action-key*) >

<!--
The deprecated element specifies the actions from an older version of the
portlet that are no longer in use and should be removed from the database.
-->
<!ELEMENT deprecated (action-key*) >

<!--
The model-resource element defines the permissions of the model.
-->
<!ELEMENT model-resource ((composite-model-name | model-name), portlet-ref, root?, weight?, permissions?) >

<!--
The organization value specifies if the model resource is an organization model
resource. The default value is false.

The portal value specifies if the model resource is a portal model resource. The
default value is false.
-->
<!ATTLIST model-resource
	organization CDATA #IMPLIED
	portal CDATA #IMPLIED
>

<!--
The composite-model-name element groups multiple model names together, which
generates a dash separated list of model names.
-->
<!ELEMENT composite-model-name (model-name+) >

<!--
The model-name element is the name of the model.
-->
<!ELEMENT model-name (#PCDATA) >

<!--
The portlet-ref element is the name of the portlet that the model belongs to.
-->
<!ELEMENT portlet-ref (portlet-name*) >

<!--
The root element is a boolean value that specifies whether the resource is
a root model resource. A root resource is the one that contains all other
resources within a portlet.
-->
<!ELEMENT root (#PCDATA) >

<!--
The weight element is a double number to control the position of the resource
in the permission GUIs. Higher values mean that the resource will appear lower.
-->
<!ELEMENT weight (#PCDATA) >

<!--
The resource element specifies an external file that contains
resource-action-mappings.
-->
<!ELEMENT resource EMPTY >

<!--
The file value specifies the external file that should be loaded to define
resource actions.
-->
<!ATTLIST resource file CDATA #REQUIRED >

=== brandonyee333/test/modules/apps/forms-and-workflow/dynamic-data-lists/dynamic-data-lists-service/src/main/resources/META-INF/resource-actions/default.xml
<?xml version="1.0"?>
<!DOCTYPE resource-action-mapping PUBLIC "-//Liferay//DTD Resource Action Mapping 7.0.0//EN" "http://www.liferay.com/dtd/liferay-resource-action-mapping_7_0_0.dtd">

<resource-action-mapping>
	<model-resource>
		<model-name>com.liferay.dynamic.data.lists</model-name>
		<portlet-ref>
			<portlet-name>com_liferay_dynamic_data_lists_form_web_portlet_DDLFormAdminPortlet</portlet-name>
			<portlet-name>com_liferay_dynamic_data_lists_web_portlet_DDLDisplayPortlet</portlet-name>
			<portlet-name>com_liferay_dynamic_data_lists_web_portlet_DDLPortlet</portlet-name>
		</portlet-ref>
		<root>true</root>
		<weight>1</weight>
		<permissions>
			<supports>
				<action-key>ADD_RECORD_SET</action-key>
				<action-key>ADD_STRUCTURE</action-key>
				<action-key>ADD_TEMPLATE</action-key>
			</supports>
			<site-member-defaults />
			<guest-defaults />
			<guest-unsupported>
				<action-key>ADD_RECORD_SET</action-key>
				<action-key>ADD_STRUCTURE</action-key>
				<action-key>ADD_TEMPLATE</action-key>
			</guest-unsupported>
		</permissions>
	</model-resource>
	<model-resource>
		<model-name>com.liferay.dynamic.data.lists.model.DDLRecordSet</model-name>
		<portlet-ref>
			<portlet-name>com_liferay_dynamic_data_lists_web_portlet_DDLDisplayPortlet</portlet-name>
			<portlet-name>com_liferay_dynamic_data_lists_web_portlet_DDLPortlet</portlet-name>
		</portlet-ref>
		<weight>2</weight>
		<permissions>
			<supports>
				<action-key>ADD_RECORD</action-key>
				<action-key>DELETE</action-key>
				<action-key>PERMISSIONS</action-key>
				<action-key>UPDATE</action-key>
				<action-key>VIEW</action-key>
			</supports>
			<site-member-defaults>
				<action-key>VIEW</action-key>
			</site-member-defaults>
			<guest-defaults>
				<action-key>VIEW</action-key>
			</guest-defaults>
			<guest-unsupported>
				<action-key>UPDATE</action-key>
			</guest-unsupported>
		</permissions>
	</model-resource>
	<model-resource>
		<model-name>com.liferay.dynamic.data.lists.model.DDLRecordSet</model-name>
		<portlet-ref>
			<portlet-name>com_liferay_dynamic_data_lists_form_web_portlet_DDLFormAdminPortlet</portlet-name>
		</portlet-ref>
		<weight>2</weight>
		<permissions>
			<supports>
				<action-key>ADD_RECORD</action-key>
				<action-key>DELETE</action-key>
				<action-key>PERMISSIONS</action-key>
				<action-key>UPDATE</action-key>
				<action-key>VIEW</action-key>
			</supports>
			<site-member-defaults />
			<guest-defaults />
			<guest-unsupported>
				<action-key>UPDATE</action-key>
			</guest-unsupported>
		</permissions>
	</model-resource>
	<model-resource>
		<composite-model-name>
			<model-name>com.liferay.dynamic.data.lists.model.DDLRecordSet</model-name>
			<model-name>com.liferay.dynamic.data.mapping.model.DDMStructure</model-name>
		</composite-model-name>
		<portlet-ref>
			<portlet-name>com_liferay_dynamic_data_lists_web_portlet_DDLDisplayPortlet</portlet-name>
			<portlet-name>com_liferay_dynamic_data_lists_web_portlet_DDLPortlet</portlet-name>
		</portlet-ref>
		<weight>3</weight>
		<permissions>
			<supports>
				<action-key>DELETE</action-key>
				<action-key>PERMISSIONS</action-key>
				<action-key>UPDATE</action-key>
				<action-key>VIEW</action-key>
			</supports>
			<site-member-defaults>
				<action-key>VIEW</action-key>
			</site-member-defaults>
			<guest-defaults>
				<action-key>VIEW</action-key>
			</guest-defaults>
			<guest-unsupported>
				<action-key>UPDATE</action-key>
			</guest-unsupported>
		</permissions>
	</model-resource>
	<model-resource>
		<composite-model-name>
			<model-name>com.liferay.dynamic.data.lists.model.DDLRecordSet</model-name>
			<model-name>com.liferay.dynamic.data.mapping.model.DDMStructure</model-name>
		</composite-model-name>
		<portlet-ref>
			<portlet-name>com_liferay_dynamic_data_lists_form_web_portlet_DDLFormAdminPortlet</portlet-name>
		</portlet-ref>
		<weight>3</weight>
		<permissions>
			<supports>
				<action-key>DELETE</action-key>
				<action-key>PERMISSIONS</action-key>
				<action-key>UPDATE</action-key>
				<action-key>VIEW</action-key>
			</supports>
			<site-member-defaults />
			<guest-defaults />
			<guest-unsupported>
				<action-key>UPDATE</action-key>
			</guest-unsupported>
		</permissions>
	</model-resource>
	<model-resource>
		<composite-model-name>
			<model-name>com.liferay.dynamic.data.lists.model.DDLRecordSet</model-name>
			<model-name>com.liferay.dynamic.data.mapping.model.DDMTemplate</model-name>
		</composite-model-name>
		<portlet-ref>
			<portlet-name>com_liferay_dynamic_data_lists_web_portlet_DDLDisplayPortlet</portlet-name>
			<portlet-name>com_liferay_dynamic_data_lists_web_portlet_DDLPortlet</portlet-name>
		</portlet-ref>
		<weight>4</weight>
		<permissions>
			<supports>
				<action-key>DELETE</action-key>
				<action-key>PERMISSIONS</action-key>
				<action-key>UPDATE</action-key>
				<action-key>VIEW</action-key>
			</supports>
			<site-member-defaults>
				<action-key>VIEW</action-key>
			</site-member-defaults>
			<guest-defaults>
				<action-key>VIEW</action-key>
			</guest-defaults>
			<guest-unsupported>
				<action-key>UPDATE</action-key>
			</guest-unsupported>
		</permissions>
	</model-resource>
</resource-action-mapping>

=== brandonyee333/test/portal-impl/test/unit/com/liferay/portal/security/permission/dependencies/default.xml
<?xml version="1.0"?>
<!DOCTYPE resource-action-mapping PUBLIC "-//Liferay//DTD Resource Action Mapping 7.0.0//EN" "http://www.liferay.com/dtd/liferay-resource-action-mapping_7_0_0.dtd">

<resource-action-mapping>
	<portlet-resource>
		<portlet-name>com_liferay_test_portlet_TestPortlet</portlet-name>
		<permissions>
			<supports>
				<action-key>ADD_TO_PAGE</action-key>
				<action-key>CONFIGURATION</action-key>
				<action-key>PORTLET_TEST_ACTION_1</action-key>
				<action-key>PORTLET_TEST_ACTION_2</action-key>
				<action-key>VIEW</action-key>
			</supports>
			<site-member-defaults>
				<action-key>PORTLET_TEST_ACTION_1</action-key>
				<action-key>VIEW</action-key>
			</site-member-defaults>
			<guest-defaults>
				<action-key>PORTLET_TEST_ACTION_1</action-key>
				<action-key>VIEW</action-key>
			</guest-defaults>
			<guest-unsupported>
				<action-key>CONFIGURATION</action-key>
				<action-key>PORTLET_TEST_ACTION_2</action-key>
			</guest-unsupported>
		</permissions>
	</portlet-resource>

	<portlet-resource>
		<portlet-name>com_liferay_test_portlet_TestPortlet2</portlet-name>
		<permissions>
			<supports>
				<action-key>ADD_TO_PAGE</action-key>
				<action-key>CONFIGURATION</action-key>
				<action-key>PORTLET_TEST_ACTION_1</action-key>
				<action-key>PORTLET_TEST_ACTION_2</action-key>
				<action-key>VIEW</action-key>
			</supports>
			<site-member-defaults>
				<action-key>PORTLET_TEST_ACTION_1</action-key>
				<action-key>VIEW</action-key>
			</site-member-defaults>
			<guest-defaults>
				<action-key>PORTLET_TEST_ACTION_1</action-key>
				<action-key>VIEW</action-key>
			</guest-defaults>
			<guest-unsupported>
				<action-key>CONFIGURATION</action-key>
				<action-key>PORTLET_TEST_ACTION_2</action-key>
			</guest-unsupported>
		</permissions>
	</portlet-resource>

	<model-resource>
		<model-name>com.liferay.test.portlet.TestModel</model-name>
		<portlet-ref>
			<portlet-name>com_liferay_test_portlet_TestPortlet</portlet-name>
		</portlet-ref>
		<root>true</root>
		<weight>1</weight>
		<permissions>
			<supports>
				<action-key>MODEL_TEST_ACTION_1</action-key>
				<action-key>MODEL_TEST_ACTION_2</action-key>
				<action-key>VIEW</action-key>
			</supports>
			<site-member-defaults>
				<action-key>MODEL_TEST_ACTION_1</action-key>
				<action-key>VIEW</action-key>
			</site-member-defaults>
			<guest-defaults>
				<action-key>MODEL_TEST_ACTION_1</action-key>
				<action-key>VIEW</action-key>
			</guest-defaults>
			<guest-unsupported>
				<action-key>MODEL_TEST_ACTION_2</action-key>
			</guest-unsupported>
		</permissions>
	</model-resource>

	<model-resource>
		<model-name>com.liferay.test.portlet.TestModel2</model-name>
		<portlet-ref>
			<portlet-name>com_liferay_test_portlet_TestPortlet</portlet-name>
		</portlet-ref>
		<root>true</root>
		<weight>1</weight>
		<permissions>
			<supports>
				<action-key>MODEL_TEST_ACTION_1</action-key>
				<action-key>MODEL_TEST_ACTION_2</action-key>
				<action-key>VIEW</action-key>
			</supports>
			<site-member-defaults>
				<action-key>MODEL_TEST_ACTION_1</action-key>
				<action-key>VIEW</action-key>
			</site-member-defaults>
			<guest-defaults>
				<action-key>MODEL_TEST_ACTION_1</action-key>
				<action-key>VIEW</action-key>
			</guest-defaults>
			<guest-unsupported>
				<action-key>MODEL_TEST_ACTION_2</action-key>
			</guest-unsupported>
		</permissions>
	</model-resource>
</resource-action-mapping>
